export const FETCH_USER="FETCH_USER"
export const LOGIN_USER="LOGIN_USER"
export const LOG_OUT_USER="LOG_OUT_USER"
export const SET_COMICS="SET_COMICS"
export const SET_LOADING="SET_LOADING"
export const SET_HERO="SET_HERO"
